"""empty message

Revision ID: 026225af88a0
Revises: d8832802705f
Create Date: 2025-03-18 13:11:17.473182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026225af88a0'
down_revision = 'd8832802705f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
